Importing necessary libraries

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler

Importing dataset

In [4]:
dataset_X = pd.read_csv('../data/processed/mobile_addiction_cleaned_final.csv')
dataset_y = pd.read_csv('../data/processed/mobile_addiction_target.csv')
y = dataset_y.values.ravel()

Dividing into training set and test set

In [5]:
X_train, X_test, y_train, y_test = train_test_split(dataset_X, y, test_size=0.2, random_state=42)

Training modal on Random Forest

In [6]:
classifier = RandomForestClassifier(n_estimators=100, criterion='entropy', random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

Evaluating accuracy

In [7]:
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)
print(cm, ac)

[[ 88 118 102]
 [117 135  95]
 [132 120  93]] 0.316
