Importing necessary libraries


In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

importing dataset

In [12]:
dataset_X = pd.read_csv('../data/processed/mobile_addiction_cleaned_final.csv')
dataset_y = pd.read_csv('../data/processed/mobile_addiction_target.csv')
y = dataset_y.values.ravel()

Dividing into training set and test set

In [13]:
X_train, X_test, y_train, y_test = train_test_split(dataset_X, y, test_size=0.2, random_state=42)

Training modal on logistic regression

In [14]:
classifier = LogisticRegression(random_state=0, max_iter= 1000)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

Evaluating accuracy

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", cm)

accuracies = cross_val_score(estimator=classifier, X=X_train, y=y_train, cv=10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))  

0.32
Confusion Matrix:
 [[ 88 130  90]
 [132 124  91]
 [120 117 108]]
Accuracy: 33.75 %
Standard Deviation: 2.87 %
